# Generated by Django 5.0.6 on 2024-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('medicine_detail', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('next_visit', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
